services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.6.1
    container_name: wowtalk-dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    container_name: wowtalk-redis
    ports:
      - "6379:6379"
