spring:
  profiles:
    default: local
  application:
    name: wow-talk
  data:
    redis:
      repositories:
        enabled: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

wowtalk:
  cors:
    allowed-origins: ${WOWTALK_CORS_ALLOWED_ORIGINS:http://localhost:3000}
