spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wowtalk
    username: wowtalk
    password: wowtalk
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

wowtalk:
  dynamodb:
    endpoint: http://localhost:8000
    region: ap-northeast-2
    room-events-table: wowtalk-room-events-local
